import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { varlockVitePlugin } from "@varlock/vite-integration";
import viteReact from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { VitePWA } from "vite-plugin-pwa";

import { pwaServiceWorker, pwaWorkbox } from "./vite-plugins/pwa-service-worker.ts";

export default defineConfig({
  server: {
    port: 3001,
    host: true,
    proxy: {
      "/trpc": { target: "http://localhost:3000", changeOrigin: true },
      "/api": { target: "http://localhost:3000", changeOrigin: true },
    },
  },
  resolve: {
    tsconfigPaths: true,
  },
  plugins: [
    varlockVitePlugin({ ssrInjectMode: "auto-load" }),
    tailwindcss(),
    // SPA mode: the shell is prerendered to /_shell.html and every route boots
    // from it on the client. No per-request SSR, so a reload works offline.
    tanstackStart({ spa: { enabled: true } }),
    viteReact(),
    VitePWA({
      registerType: "autoUpdate",
      // TanStack Start renders its own document (there is no index.html to
      // transform), so the manifest link and SW registration are wired in by
      // hand: see `__root.tsx` and `components/pwa-register.tsx`.
      injectRegister: false,
      outDir: "dist/client",
      includeAssets: ["icon.svg", "apple-touch-icon.png", "favicon-64.png"],
      manifest: {
        name: "MeldSpace",
        short_name: "MeldSpace",
        description:
          "A peer-to-peer collaborative room where the room itself is the shared object.",
        start_url: "/",
        scope: "/",
        display: "standalone",
        background_color: "#0B0C0D",
        theme_color: "#0B0C0D",
        icons: [
          { src: "/pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "/pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            src: "/pwa-maskable-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      // Declared here so the options stay in one place, but generated by the
      // `pwaServiceWorker` plugin after Start's post-build. See that file for
      // why `vite-plugin-pwa` can't build the worker itself.
      workbox: pwaWorkbox,
      // A service worker in dev would cache the shell and fight HMR. Keep it
      // off; test offline against a production build + preview.
      devOptions: { enabled: false },
    }),
    pwaServiceWorker(),
  ],
});
